const frases = [
  // 'Se a vida fosse um jogo, te amar seria o meu gol nos acréscimos, como nos jogos mais tensos do Curica.',

  // 'Eu amo amar você, nunca se esqueça disso...',

  '📅 25/09/2024 - Dia 00: Hoje foi um dia diferente de todos os outros, onde você me liga depois de uma briga com seu pai (confesso que achei estranho), eu queria muito te ver depois disso e ofereci carona para ir trabalhar, que por algum motivo sabia que era exatamente o que precisava. E ver você vestida de mostarda, nosso misto quente em um dos meus lugares favoritos só me fizeram ver o quão importante são esses momentos com você e nesse dia, posso dizer que me apaixonei(de novo). A noite, quando fomos no parque das aguas, foi uma noite diferente de tudo, ali tivemos conversas aleatorias, conversas sérias, brincamos, falamos mal dos outros, etc... uma noite perfeita (quero que todos nossos dias sejam assim). ',

  '📅 26/09/2024 - Dia 01: Depois do dia de ontem, eu queria muito te ver e então fiz a educação positiva para ter alguma forma de ver você (KKKKKKKKKKKKKK), e por sorte, você aceitou que eu te levasse para o trabalho (que manha maravilhosa), insisti para você meter o loko no trampo, eu queria muito ter sua companhia, não precisariamos fazer nada, só queria ta com você perto. O livro que baixei para você, vai ficar para sempre marcado como uma lembrança de você. Mesmo eu querendo muito, eu não imaginava que iriamos se ver de novo, e no fim você quis tomar sorvete e passar a noite comigo (que dia meu amigo), não deveriamos ter feito nada nesse dia, os dois estavam tensos,  aceleramos muito o processo e você acabou aceitando ser a minha ficante plus ultra master 4k.',

  '📅 27/09/2024 - Dia 02: Eu cheguei a sonhar com você nesse dia, e bateu uma saudade surreal (nem parecia que tinhamos se visto na noite anterior). Fiz educação positiva de novo e tive a melhor resposta que poderia ter recebido (você queria me ver tanto de manha quanto de noite). Essas manhãs se tornaram algo que quero fazer todos os dias, quero poder tomar café com você, te levar para o trabalho (até o dia que você vai ser minha esposa trofeu e não vai trabalhar nunca mais) ou seja, te ver todos os dias. A noite, quando fomos com o cice no shopping sorocaba, não sei explicar, mas tinha alguma coisa diferente ali e quando chegamos em casa, eu percebi que tava me sentindo muito mais confortavel com você do que nunca, tivemos sim uma conversa dificil (extremamente necessaria para o nosso recomeço) e de verdade? Quero muito finalizar ela para que possamos seguir juntos. Uma coisa que me falou a noite, eu entendi perfeitamente. Você vai amar alguém como me ama e vai receber um amor tão intenso quanto o meu (Spoiler: eu vou essa pessoa na sua vida). Não é por costume da rotina ou qualquer outra coisa, é pelo sentimento que um tem pelo outro, a pergunta que finalizei a noite, é justamente o que eu quero: ME DEIXA ENFRENTAR SEUS MEDOS COM VOCÊ?',

  '📅 28/09/2024 - Dia 03: Hoje foi um dia que eu queria muito te ver, muito mesmo (confesso que tava com saudades), mas queria também que aproveitasse o seu date (mesmo sabendo que ninguem é tão interessante quanto eu, tava com um pouco de ciumes). E quando você me chamou para sair, foi a melhor noticia que poderia ter tido e de verdade, a noite foi incrivel, mesmo eu tendo aquele sonho merda que me deixou bem abalado, a noite foi gostosa... Quero te pedir desculpas por quase falar as "tres palavras", perdi um pouco a linha. Quero ter mais noites como essa, você me permite ter?',

  '📅 29/09/2024 - Dia 04: Eu confesso que não ia te chamar para nada hoje, mas quando minha mãe falou para você almoçar em casa, só cedi aos pensamentos e te chamei (KKKKKKKKKKKKKKKKKKKK), mas ao mesmo tempo, queria que aproveitasse o seu momento e o seu dia (afinal, se vimos a semana toda), não deu certo da gente se ver, mas no final fiquei feliz com você usando educação positiva pra gente se ver amanhã. Eu fiquei muito puto hoje, parece que é crime eu fazer as coisas que eu quero com quem eu gosto, pqp... E no final da noite, quando a gente conversou até você dormir, eu gostei muito, foi muito gostoso, me acalmou e também foi diferente (não sei explicar)',

  '📅 30/09/2024 - Dia 05: Ainda bem que deixei para escrever no final do dia (KKKKKKKKKKKKKK), hoje aconteceu bastante "coisinhas", gostei muito do dia (por mais dias assim), não quero que pense que eu entendi errado as perguntas e tals, pelo contrario, eu entendi onde queria chegar com aquilo (são perguntas extremamentes importantes) e claramente que gostei de você falando que queria me ver, de falar que sou seu ficante ultra blaster 4k (KKKKKKKKKKKKK), confesso que fiquei com um pouco de medo da nossa conversa no final do dia, mas o que eu falei é sério, guarde somente as coisas boas do nosso relacionamento e vamos construir algo do zero, por isso que o "dia00" foi no dia 25/09/2024, que nesse dia algo mudou e acho que ali foi um marco. ',

  '📅 01/10/2024 - Dia 06: Não sei explicar o que eu senti nesse dia, mas foi algo bom. Eu falando abertamente o que eu queria fazer e a noite, mesmo com pouco tempo juntos, foi maravilhoso, sério mesmo. As consultas com a psicologa me ajudam a cada vez mais entender meu sentimento por você e com tudo o que ta acontecendo, e cada dia que passa você se torna mais e mais importante na minha vida (sempre foi, mas agora é diferente), falo com toda certeza que você é uma das coisas mais importante na minha vida. O que eu falei ontem sobre o salto que minha vida pode dar é verdade, e é tudo graças a você, justamente por isso que eu não acredito que tudo que aconteceu entre a gente seja algo passageiro, eu acho que você é alguém para ficar (quero que fique)... Eu espero muito que no nosso recomeço você seja a minha esposa trofeu e escolha ficar comigo até eu ficar bem velhinho e que possamos viajar o mundo juntos e fazer todos nossos planos darem certos (são muitos)...',

  '📅 02/10/2024 - Dia 07: Queria ter visto o eclipse com você, mas quase não deu para ver em SP. O dia todo foi maravilhoso, principalmente o fato da gente tomar café juntos e queria muito ter uma foto sua com a florzinha na orelha, ainda mais hoje que tava toda menininha, ficou perfeito (HOJE ME APAIXONEI UM POUCO MAIS POR VOCÊ). Confesso que fiquei pensando na volta do seu ex maluco, ele me deixou muito puto com tudo que te falou (maluco babaca) e confesso também que me deixou com um pouco de ciumes (KKKKKKKKKKKKKKKK), mas quando ele falou de "ficantezinho" e começou a meio que te ofender o sangue subiu na hora, acho que faria merda real se encontrasse com ele. Fiquei pensando também que você meio bebada e eu ainda sim cuidando de você para não dar muito na cara que tava triloca. Vou te confessar outra coisa com base nisso, o que eu falei é verdade, se fosse o "meu antigo eu", eu iria ficar puto com você e talvez iriamos ter uma leve discussão por causa disso, mas eu achei engraçado e fiz o que sempre deveria ter feito quando fosse o caso CUIDAR DE VOCÊ e não te julgar (E isso só me fez desenrolar mais o que eu sinto)... ',

  '🌑 EXTRA - SEMANA 01 🌑: Essa primeira semana da gente foi maravilhosa, pode parecer que não, mas você me mostrou bastante coisa do que eu quero (acredito que sejam atitudes involuntarias), confesso que tava negando muito meus sentimentos, mas depois que meu amigo falou que a gente ta num dos melhores momentos que poderiamos estar, que é a fase de se conhecer de novo (fiquei pensando muito nisso), eu sei que a gente já ta se conhecendo de novo, mas quero que deixar bem claro que vou tentar te reconquistar todos os dias da minha vida até você chegar no momento que vai falar que não quer mais me ver nem pintado de ouro (eu apareco pintado de prata ou verde KKKKKKKKKKKKKKKKK), você já sabe de tudo isso, né? Então Yasmin, eu vou te esperar, não quero conhecer ninguem, então saiba que... caso você me permita ter você de novo num relacionamento, eu to esperando com bolo, coquinha de café e seu mistão quente... Volto a dizer, o nosso recomeço tem tudo para ser lindo, você já viu o quanto to diferente, ou seja, aquele Alan que conheceu, morreu e nunca mais vai voltar. Sei que ta confusa, quer desenrolar os sentimentos, aproveitar a vida e tals, mas independente de tudo, quero enfrentar tudo com você e te provar como seremos melhores juntos... OBRIGADO POR SER ESSA PESSOA INCRIVEL NA MINHA VIDA, MEU PUDINZINHO KKKKKKKKKKKKKK ',

  '📅 03/10/2024 - Dia 08: O dia de hoje foi diferente de tudo, confesso que achei bonitinho você com medo de eu cansar de você  KKKKKKKKKKKKKKKKK (não vou cansar e nem desistir de você, saiba que vou te esperar o tempo que for necessario, e não esqueça, eu to no seu podio). eu me emocionei com o que me falou sobre mim, não esperava que ia me sentir tão feliz com o que me falou a ponto de chorar (quanto tempo que isso não acontece), principalmente quando falou que iria contar sobre mim para seus filhos e neto (porra, isso me pegou demais. foi de longe a coisa mais bonita que alguém falou de mim)... nossa conversa foi necessaria e de novo, eu sei que não ta pronta namorar de novo por varios motivos e que estamos se conhecendo de novo, mas ainda aguardo ansiosamente o dia que vai me procurar para tentarmos de novo... espero que possamos ir alinhando tudo ao decorrer dos meses para que possamos seguir novamente juntos, e no final, eu concordo com você é "cedo demais", fiquei pensando sobre isso e concordo com quase tudo que falou, só não concordo com o que falou de voltarmos agora e ser tudo bom e voltar a ser zoado (eu duvido que isso aconteceria de novo), mas saiba que você tem meu coraçãozinho pra você, e sempre vai ter. meu unico pedido é para que não vá embora da minha vida, eu sempre vou querer sua companhia... cara, você tem noção do quão importante você é pra mim?????? vou te esperar o tempo que for e não te falei, mas vou eternizar você no meu corpo junto com a tatugem do maktub que gosta... espero que não fique um clima zoado entre a gente e saiba que to aqui para enfrentar todos os seus medos e inseguranças para que possamos ser um casalzão da porra (KKKKKKKKKKKKKKKKKK). obrigado por tanto, não sei como te agradecer, acho que se eu te der o mundo não é o suficiente para te mostar o quão imporante você é, mas é isso lek, tmj',

  '📅 04/10/2024 - Dia 09: Quero começar isso aqui te pedindo desculpas por ta chatinho na hora que te encontrei a noite (queria muito te ver), achei muito fofinho você se preocupando comigo e segurando minha mão (tão fofinhaaaa)... eu não tinha pensado no que falou sobre a gente no inicio de tudo, que você também não queria um relacionamento e mudou de ideia, quero que seja livre e leve, não com pressão nem nada do genero. Só para você ter certeza, não vou embora da sua vida e não quero que você va embora também (quero você comigo quando eu conquistar o mundo), e para deixar eternizado, eu penso em você todos os dias e o tempo todo, você não precisa fazer nada para isso acontecer. E ai gatinha, ta afim de viver um romance periculoso comigo???? (KKKKKKKKKKKKK)',

  '📅 05/10/2024 - Dia 10: Hoje foi um dia que nem conversamos direito (senti sua falta pra caralho), mas eu sei que tava curtindo o rolê com sua familia e espero muito que seu dia tenha sido muito, muito, muito, mas muito bom mesmo... Confesso que fiquei imaginando como seria eu com você em SP, conhecendo seus familiares e a gente se divertindo junto (será que isso um dia vou ter essa oportunidade de novo?). O lance do meu pai me deixou desconfortavel, que eu sei que a ideia dele é boa, mas porra, ficar te enchendo o saco assim, você já tem muita gente que te enche o dia todo (eu me incluo nisso), foi mal, de verdade... Nem preciso falar que queria muito te ver hoje e provavelmente amanha também sinta essa mesma vontade, mas eu sei que quer passar esse seu tempo com você mesmo... Meu sonho de princesa seria você me chamar amanha para ir votar com você KKKKKKKKKKKKKKKKK',

  '📅 06/10/2024 - Dia 11: Infelizmente meu sonho de princesa não se realizou, mas tudo bem (ou não) KKKKKKKKKKKKKK. Fiquei muito feliz em saber que sua familia acabou perguntando de mim, mas ao mesmo tempo fiquei meio pá pensando que isso poderia ter sido um incomodo de alguma forma (sei lá, minha cabeça não para tem hora), e fiquei muito contente de trazer o sabonetinho de lembrança pra mim (não sei explicar o que senti, mas o coração ficou quentinho). Quando eu fui votar, eu lembrei de como eu tinha planejado esse dia com você, que era você me acompanhando na votação aqui perto de casa, a gente almoçando juntos e a tarde indo votar com você para passar o dia juntos assistindo filme. E quando você usando de estrategias ardilosas para eu te buscar amanha, foi muito bonitinho KKKKKKKKKKKKKK',

  '📅 07/10/2024 - Dia 12: Sabe, hoje foi diferente... Principalmente quando "mandou" eu ir te buscar e eu só aceitei KKKKKKKKKKKKKKK, nós passamos de certa forma, o dia todo juntos e foi muito gostoso e engraçado, quando eu soprei sua boca e sua barriguinha foi enchendo parecendo um balão, foi intankavel pra mim (vou fazer mais vezes isso, gostei). Quero ter muito mais dias assim... Na hora que fomos na demarto, comprar remedio e tudo mais, senti uma coisa bem diferente, não sei dizer exatamente o que é, mas foi algo gostoso de sentir (acho que to apaixonado por você(só acho))... ',

  '📅 08/10/2024 - Dia 13: Quando fui te buscar e percebi a cara que você tava para fazer o exame, confesso que fiquei com medo, parecia que iria a qualquer momento me matar e me comer (mas ainda sim tava brincando com o perigo KKKKKKKKKKKK) e na hora que você amassou os lanches, fiquei extremamente surpreso e a foto que tirei, vai ficar marcado pra sempre como "o dia que alimentei meu dragãozinho" KKKKKKKKKKKKKKKKKKKKKK Queria ter passado o resto do dia com você, mas só não falei para fazer isso, por que tinha que fazer suas coisinhas na sua casa, mas saiba que era o que mais queria.',

  '📅 09/10/2024 - Dia 14: Cara, não tenho palavras para o dia de hoje, aconteceu quase tudo que poderia acontecer num dia (sério mesmo). Não gostei de passar esse dia com você, eu amei passar ele com você (não tiraria nada do que aconteceu). Eu senti muito que eramos um casal (peço até desculpas se em algum momento eu confundi as coisas), mas isso é para você ter uma noção de como seria caso você libere uma vaguinha de namorado ai KKKKKKKKKKKKKK (não esqueci que sou o dono do primeiro lugar). Quero ter muito mais dias com você assim, sério mesmo... A unica coisa que eu posso garantir, é que vai ser cada dia melhor...',

  '🌒 EXTRA - SEMANA 02 🌒:  E assim fechamos a nossa segunda semana desde que se "conhecemos", não posso dizer que tivemos altos e baixos, que estamos basicamente em perfeita sintonia. A parada com a minha mãe mexeu muito comigo, mas eu sei que é extremamente necessario o que ela falou e saiba que não tem motivo de você parar de vir em casa, até por que eu sei que ela não iria ligar e eu to falando sério com isso (sempre que quiser vir, você sempre vai ser bem recebida). Sabe, eu acho que da forma que estamos indo, ta fluindo muito bem e concordo que ainda é cedo para voltar, alias deu só 1 mês que estamos separados (obviamente que deu para notar a diferença em ambos), mas saiba que eu vou continuar melhorando por mim acima de tudo, mas claramente é com aquele fiozinho de esperança que o nosso recomeço vai ser lindo, saiba que eu vou esperar você ficar pronta para assumir um relacionamento de novo e não vou me arrepender nem um pouco disso, então Yasmin, eu to te esperando aqui para você ser minha esposa troféu!',

  '📅 10/10/2024 - Dia 15: O dia foi muito bom (como vem sendo todos os dias), a minha lembrança favorita agora é da gente tomando café em um dos meus lugares favoritos (quero ter muito mais dias assim)... Eu gosto de fazer tudo com você, te buscar/levar para o trabalho, te irritar, cuidar de você, tomar café com você, te abraçar, te cheirar, enfim, tudo... O que eu falei de noite é verdade, não quero ninguem melhor pra mim, quero que você se torne a melhor pessoa pra mim, da mesma forma que não quero que você encontre alguém melhor que eu, eu vou ser o melhor pra você. Sei que algumas coisas que eu falei foram "pesadas", e não, não vou te pedir desculpas por isso, meu unico pedido é para que me deixe mostrar o meu amor para você e te provar que você merece sim ser amada... Eu não quero ficar nem um dia sem falar com você, quero falar e te ver todos os dias da minha vida, até ficar bem velhinho, então, pare de loucura e me deixe entrar para enfretar tudo o que tem medo/insegurança junto com você.',

  '📅 11/10/2024 - Dia 16: Mesmo sendo rapidinho, gostei de ter comido o mistão com você KKKKKKKK e to extremamente ansioso para irmos para SP juntos, acho que vai ser bem gostoso.... quero ir no parque da juventude com você e conhecer o museu, quero fazer muitas coisas com você lá... Mesmo eu te vendo de manha, confesso que fiquei meio chateado por não te ver a noite, que você quis ir com seu pai e quando sumiu, fiquei mais chateado ainda, senti que meio que não queria minha companhia, sei lá, algo desse genero, sabe... Enfim, quando apareceu a noite e me contou o que foi, fiquei mais aliviado que você tava bem, mas ainda me sentindo meio esquisito (loucura né? KKKKKKKKKKKKKK)',

  '📅 12/10/2024 - Dia 17: Confesso que tava animado para ir com você na espaço laser, mas quando desmarcou ontem, eu já sabia que não iria te ver hoje (foda), queria ter passado o dia com você, mesmo sabendo que iriamos passar o dia todo juntos amanhã... E quando te chamei, minha mãe pediu para comprar sorvete e falou "pega um que a Yasmin goste também, vai que ela venha aqui, pelo menos tem algo gostoso para ela", e confesso que tinha esquecido do seu compromisso...',

  '📅 13/10/2024 - Dia 18: Cara, hoje não tenho como te explicar o quão gostoso foi o dia, sério mesmo, não tenho palavras para descrever e tenho uma cena marcada na minha cabeça, que é você andando na paulista toda contente, animada com tudo que via, sério, isso pra mim foi a melhor coisa que poderia ter acontecido... Sei que em alguns momentos não fui uma companhia tão boa, mas eu só tava com medo de estragar o dia, que quase fiz isso... Espero que sempre lembre desse dia e que possamos ter mais dias assim, foi incrivel com TODAS AS LETRAS, OBRIGADO POR SER TÃO BOA PRA MIM (MESMO EU NÃO MERECENDO)',

  '📅 14/10/2024 - Dia 19: Hoje fiquei meio pa, por que queria ir te buscar para ir trabalhar e te ver um pouco (acho que era necessario depois de ontem), mas fiquei muito feliz de você querer me ver a noite para conversarmos (você ta me devendo um abraço), pena que a reunião atrapalhou nossa conversa, mas conseguimos conversar e se ver um pouquinho, foi bom...',

  '📅 15/10/2024 - Dia 20: Por mais que eu tava meio pa, gostei de ter ido te levar trabalhar (faltou só levar seu mistão) e sério, fiquei muito pensativo com a merda que te falei do "relacionamento CLT", sei que não é assim e nunca foi, não quero te cobrar de falar comigo (você não tem obrigação nenhuma de me responder). Confesso que não quero parar de ficar com você, quero continuar até você ir embora, mas vou respeitar sua decisão (só não quero que você fique sem falar comigo), sei que você tava bem ocupada, mas ainda sim senti muita sua falta durante o dia.',

  '📅 16/10/2024 - Dia 21: Hoje percebi que você não tava muito afim de conversar comigo e confesso que queria muito te mandar mensagem, mas por algum motivo sei que você só não ta no clima para conversar comigo (e ta tudo bem, ou não). Gostei de ter feito o monstrão quente para você, é minha nova especialidade para te mimar um pouco ou fazer seu café da manhã KKKKKKKKKKKKK espero que você esteja lendo ainda isso aqui e que fale comigo (to com medo de te incomodar, se mandar mensagem)... Obrigado por tanto, não desiste de mim, ta?',

  '🌓 EXTRA - SEMANA 03 🌓: Essa semana teve tanta coisa que chega a ser estranho, acho que precisamos parar de viver tão intensamente assim, nesse tempo que a gente passou junto, acontece tanta coisa que é historia de anos. Saiba que não tenho esperança da gente voltar, mas ainda não vou desistir de você, quero muito que seja você (de verdade). To ansioso para ir com você sabado mexer no seu cabelo e quero te ver bonitona sempre. Sei que nos ultimos dias não estamos falando muito, mas saiba que sempre fico esperando uma mensagemzinha sua, então caso queira falar comigo, você sabe onde me achar...',

  '📅 17/10/2024 - Dia 22: Hoje foi um dia bem esquisito pra mim (não com você, longe disso), mas confesso que gostei da nossa conversa sobre as coisas, inicialmente eu queria que você ficasse com as coisas, mas depois eu entendi o motivo e concordo plenamente com você. Não me deu nem uma sensação ruim quando eu queimei e descartei as nossas lembranças daqui, pelo contrario, como começou a sair uma chama escura, eu entendi que era extremamente necessario... Por mais que eu queira muito ir com você sabado fazer o seu cabelo, eu te mandei o dinheiro para você ir com alguem que te deixe mais confortavel e quando você tiver bem, você me procura, ta? Eu vou atualizar esse site todos os dias, quando eu não tiver nada para falar, vou colocar alguma lembrança nossa e to esperando você aqui, você sabe onde me encontrar e para você saber, na tela inicial desse site, onde ta meu nome, direciona para o meu whatsapp, então caso em algum momento perca meu numero, só voltar nesse site e clicar ali, vai mandar direto para a nossa conversa.',

  '📅 18/10/2024 - Dia 23: Queria muito te ver hoje, te dar um abraço, um beijo, enfim... Eu vou respeitar todo o espaço que você quiser/precisar e saiba que sempre estarei aqui te esperando com todo o amor que eu tenho a oferecer para você. Ta sendo muito ruim não te mandar algo te enchendo o saco, contando sobre o meu dia, enfim, ta sendo ruim ficar sem conversar com você, mas eu só to respeitando o espaço que você precisa.',

  '📅 19/10/2024 - Dia 24: O que me falou hoje de "estavamos tentando ter algo de novo" me pegou muito, de verdade... Igual eu te falei essa semana, não é por que eu não tenho mais esperança da gente voltar, que eu desisti de conquistar você. Grande parte do que eu sempre falei de recomeçar, eu mesmo não to cumprindo, que é a parte da gente ser amigo e eu ir ganhando seu coraçãozinho pouco a pouco. Ou seja, pulamos algumas etapas ai de novo... Saiba garota que quando você se achar merecedora do amor e quiser o meu amor de volta, eu sempre vou te amar da forma mais intensa que eu conseguir, com a unica diferença que esse amor vai ser por mim também, não só por você.',

  '📅 20/10/2024 - Dia 25: Hoje fiquei o dia todo pensando em você, principalmente no domingo passado (tava tão gostoso, que queria ficar naquele dia), quero mais dias como aquele e espero muito que um dia possamos voltar em SP e conhecer mais lugares. Você não tem noção o quanto eu quero te mandar mensagem te enchendo o saco sobre alguma coisa, de te ver, te fazer o mistão, cara, to com saudades de você... Uma verdade nua e crua? Queria muito que você me desse só mais uma chance pra gente poder voltar a ficar. Desfazer todo aquele laço amoroso do nosso antigo relacionamento e tentar mais uma vez a ter algo, porra, não é possivel que esses dias bons que a gente sempre teve, seja tão pior do que as dificuldades que nós temos, pensa com carinho Yasmin, vamos resolver todos nossos problemas para que possamos tentar de novo mais pra frente? (de preferencia na europa)',

  '📅 21/10/2024 - Dia 26: Gostei muito de ter ido no hospital com você, acho que eu ter "forçado" ir com você foi uma coisa boa... A ideia era conversamos sobre as coisas e também pegar as nossas coisas para descartar, mas não deu certo para pegar (uma desculpa para eu voltar KKKKKKKKKKK). Eu quero seguir a ideia de descartar tudo e reconstruir os nossos laços, queria muito pedir pra gente voltar a ficar, mas não pedi, por que tem que ser algo natural (livre e leve) e vai acontecer o que tiver que acontecer...',

  '📅 22/10/2024 - Dia 27: Gostei muito de passar o dia com você, mas gostei muito mesmo, principalmente de ver você ficando bonitona com o cabelo e também de arrumar a casa com você e a Iris KKKKKKKKKKKKKKK (foi estranhamente legal)... Acho muito engraçado o como todo mundo vê o quanto eu te amo/gosto de você, será que tenho que parar de demonstrar tanto assim? Cara, na hora que a gente ta no terminal e você tava na minha frente, eu senti uma vontade incontrolavel de te beijar, você vindo bem pertinho de mim, teve uma hora que eu quase fui (confesso que queria muito)... Você enganchando no meu braço foi muito bom, ainda mais lembrando da memoria de SP, você permite ter mais dias assim? To extremamente ansioso com o role de sabado, quero muito que chegue logo. ',

  '📅 23/10/2024 - Dia 28: Foi bem legal ver minha mãe fazendo a camiseta pra você, ela toda animada fazendo (ficou o dia todo fazendo isso) e perguntando pra mim se você ia gostar ou não KKKKKKKKKKKKKKKKK queria muito te ver hoje (igual eu quero todos os dias), to com saudades... Aproveitei a deixa da minha mãe para te chamar pra vir aqui (unir o util e o agradavel) e cara, quero muito ver você com a fantasia do ben10 e se divertindo.',

  '🌕 EXTRA - SEMANA 04 🌕: Essa semana não tomamos café nenhum dia no "nosso lugar favorito", queria comer um mistão e falar merda com você lá KKKKKKKKKKKKK queria também que a gente saisse sem horario para voltar, conversar, brincar, falar merda, se pegar, transar, enfim, tudo o que tiver direito... O que eu falei na segunda é verdade, quero muito voltar a sair sem compromisso com você, muito mesmo. Acredito que os nossos ultimos dias, fazem valer a pena, não? KKKKKKKKKKKK Nesse mes aconteceu tanta coisa entre a gente, que chega a ser estranho. Na semana que não conversamos muito, eu senti MUITO a sua falta, mas MUITO mesmo e com a minha mãe quase implorando para eu não te perder mexeu muito comigo e cara, não quero te perder e espero muito que possamos ter muitos anos juntos, afinal, a minha fortuna vai ficar para você KKKKKKKKKKKKKKKK',

  '📅 24/10/2024 - Dia 29: Queria ter te visto hoje, senti sua falta (confesso que não queria sentir sua falta desse jeito)... Eu não tenho muito o que falar hoje, só queria que você soubesse que não vou desistir de você tão facil assim, ainda tenho esperança na gente. Quero você do meu lado como minha parceira, não só como minha amiga...',

  '📅 25/10/2024 - Dia 30: Eu to muito ansioso para amanhã, sério mesmo, quero ver você se divertindo, dando risada, ficando doida KKKKKKKKKKKKKK principalmente, quero me divertir com você... Foi bom ter te visto hoje, mesmo com o carro zoando, eu ainda peguei do meu irmão só para te ver de novo (tenho parar de ser assim com você). O que eu falei é verdade, eu ainda tenho esperança da gente voltar a sair sem compromisso, não só como amigos, não quero forçar nada, quero que seja natural e tals, enfim, é isso lek, tmj KKKKKKKKKKKKKK',

  '📅 26/10/2024 - Dia 31: Sinceramente, não queria escrever nada hoje, mas promessa é divida, né? Algumas cenas estão marcadas na minha cabeça, mas no final, o que mais marcou foi a gente conversando no BK. Vou te confessar por aqui, eu fiquei muito pensativo com tudo que me falou e cara, as vezes sinto que não fui algo bom na sua vida, senti que te forcei algo no namoro. Quero muito você de volta, todo mundo fala para eu não desistir de você, te conquistar de novo, enfim... EU NÃO VOU DESISTIR DE VOCÊ, mas vou te acompanhar de longe, na esperança de você aceitar todo o meu amor por você. Quando você aprender a se sentir amada e quiser tentar de novo, saiba que eu to te esperando. EU TE AMO GAROTA, NÃO SE ESQUEÇA DISSO.',

  '📅 27/10/2024 - Dia 32: Fiquei pensando em você o dia todo hoje, e confesso que pensei que você nem iria mandar a solicitação de novo ou até mesmo mensagem. Você tinha que ter visto o sorrisinho bobo que eu dei quando vi sua mensagem, acho que no final, de fato estamos realmente recomençando / reconstruindo laços. Não precisa se preocupar, estamos bem e fiquei feliz pelo seu pedido a Deus, obrigado.',

  '📅 28/10/2024 - Dia 33: Queria ter te visto hoje, e tudo que falei por mensagem é verdade...Me pegou muito o que mandou hoje sobre a gente, e saiba que eu quero que seja algo sem pressão também, que seja algo de fato leve. Ta tudo bem não saber o que quer, eu sei por ter pensado muito nisso... Saiba que só vou desistir de você se você me pedir, caso contrario, vou continuar tentando te conquistar de pouquinho e pouquinho... Sabe, acho que o principal motivo de eu querer te ver hoje era para te falar "podemos tentar de novo?" ou até mesmo "vamos tentar só mais uma vez, mas diferente de tudo".... Queria que você lesse isso e me mandasse que queria tentar só mais uma vez, quando falo de tentar, é tentar para valer, se caso um dos dois tiver medo, conversar com o outro, se algo não agradar, conversar e resolver para não ficar nada de sentimento ruim... Não existe mais aquela ruina que a gente tinha conversado, posso dizer qtudo aquilo virou pó, nós demolimos aquilo para reconstruir algo do zero e para tudo isso acontecer, precisamos de uma base solida... Bom, acho que tenho muito para dizer sobre a gente KKKKKKKKKKKKKK',

  '📅 29/10/2024 - Dia 34: Eu não tenho como descrever o que senti hoje, foi algo muito engraçado e gostoso KKKKKKKKKKKKKK Quero muito mais dias desse jeito... E mais uma vez, eu fiz o que deveria sempre fazer, cuidar e entrar na brisa com você e não te julgar/ficar bravo... Eu cantando com você a musica da Marina Lima ficou marcado na minha cabeça... Uma verdade nua e crua? Meu coraçãozinho errou um pouco as batidas ontem e isso me assustou um pouco... Obrigado por tanto e continue sendo essa pessoa incrivel.',

  '📅 30/10/2024 - Dia 35: Mano, eu gostei muito de ter ido te buscar na faculdade, foi bem engraçado... Mesmo o carro zoado, fiz uma gambiarra só para te ver mais um pouquinho (talvez eu seja muito besta de você), você não tem noção do quanto eu penso em você, passo o dia todo pensando em te encher o saco com alguma coisa, em te dar um beijo, sei lá, penso tudo sobre você... O sonho de hoje tiveram varias perguntas sobre a gente e a maioria ficou marcada na minha cabeça, todas as pessoas que aparecem no sonho estão com semblante extremamente sério e o foco sempre é de como seria diferente, cara, foi surreal...',

  '🌕 EXTRA - SEMANA 05 🌕: Confesso que não tenho muito o que escrever sobre essa semana, foi uma montanha russa de emoções, fui do céu ao inferno em segundos e não sei dizer o que senti nela toda. a nossa conversa de segunda me pegou um pouco, por algum motivo, mesmo não querendo nada sério agora, eu ainda insisto em tentar te reconquistar e reconstruir tudo com você e tentar algo de novo, confesso também que me senti um pouco como step emocional com algumas mensagens (sei que não é o caso), to começando a achar que é um crime querer te esperar/ter algo com você, mas ainda sim não consigo não ter essa leve esperança e se for um crime, me prenda',

  '📅 31/10/2024 - Dia 36: Feliz Halloween gatinha! Queria muito que a gente fosse numa festa a fantasia hoje e infelizmente não achei a flor com a abóbora para te dar... Mesmo você chatinha, eu gosto de passar um tempo com você, eu só fico quieto, por que eu sei que quando você ta assim, você fica "pokas ideias" KKKKKKKKKKKKKKKKK Eu queria muito que você tivesse respondido minhas perguntas de hoje, mas vou deixar para quando a gente sair (se isso acontecer) e tivermos tempo para conversar direito... Eu pensei muito nessa semana sobre o que eu quero com você e como pretendo levar as coisas daqui pra frente e uma coisa que posso garantir é que vai ser sem pressão nenhuma e eu vou te esperar até você não ter duvida nenhuma, saiba que toda a confusão que existe em você, eu quero descer ela na porrada para te provar que não vai se arrepender.',

  '📅 01/11/2024 - Dia 36: Foi uma noite muito esquisita hoje, de verdade... Queria sim ter passado um tempo com você, mas não desse jeito. Fiquei pensando muito sobre tudo o que falou, e o que mais me pegou é você falando que "nunca foi reciproco o sentimento", mano, acho que ninguem ta pronto para ouvir isso, né? Espero que eu tenha interpretado errado, espero muito, muito mesmo... Eu ainda to procurando palavras para mudar a parte do "te esperar", mas até agora não encontrei nada para tirar essa pressão sobre isso.',

  '📅 02/11/2024 - Dia 37: Confesso que fiquei esperando o dia todo você me falar que queria sair pra gente poder ir no pagode ou qualquer outro lugar (sinceramente, não sei por que insisto tanto em sair com você), confesso que fiquei levemente bravo quando você saiu e pareceu que só sabia negar o meu pedido ou sei lá esperando algo melhor aparecer, algo do gênero, sabe? que eu te chamei na terça (eu acho), eu sei que aconteceram algumas coisas que mudaram tudo e tals, não sou chato/hipocrita nesse nível, mas não consigo controlar o meus sentimentos… foda… na hora que vi o lance do outback, a primeira coisa que pensei foi em pagar minha promessa pra você e o que eu lembrei, foi que no dia que iríamos você esqueceu e marcou outra coisa kkkkkkkkkkkk',

  '📅 03/11/2024 - Dia 38: Gostei de ter ido no outback com você, finalmente minha promessa tá paga (demorou só 6 meses), achei muito estranho você me perguntar sobre gostar de sair com você, mas igual eu falei, quem tem motivos para não gostar de sair comigo é você, por que não consigo esconder meus sentimentos e você sabe das minhas intenções com você, você sabe muito bem ainda, isso já é um motivo muito grande para não querer sair comigo. achei meio estranho ter insistido tanto para a Iris vir junto, mas até que entendo o porque e eu gosto de sair com ela, sempre me divirto com as merdas que ela fala KKKKKKKKKKKKKKK O filme foi uma merda, teve sim alguns momentos bons, mas no geral, achei bem ruim... E não sei por que você nunca acredita em mim, mas eu não falei nada para o Cicero sobre isso do que tava falando de "hortelaria", lembro que comentei com ele que direito não é a area que iria ganhar a vida e arqueologia seria o seu hobby, mas foi só isso... Sabe, as vezes eu acho que o problema sou eu no rolê, muitas vezes a gente ta tendo uma noite legal e você se irrita e acaba "rasgando" ou ficando extremamente estressada, sempre começo a me comparar, pensando que se fosse qualquer outra pessoa, você não faria isso.',

  '📅 04/11/2024 - Dia 39: Senti muito sua falta de manha, meu dia foi bem zoado por não ter visto você cedo (fica intakavel o dia KKKKKKKKKKKKKK), mas em compensação, gostei muito de ver você sendo modelo e do resultado... Tivemos uma conversa necessaria e mano, só consigo te dizer que eu quero fazer tudo o que te falei, não vou deixar de tentar te reconquistar, entendo tudo o que falou e de verdade, ta tudo bem. Eu coloco todos os pontos na balança, principalmente as coisas ruins, que isso me assusta em tentar algo de novo com você, mas eu to disposto a enfrentar todos os meus medos só para te ter uma unica vez. Eu falo tanto de ser uma ultima vez por causa disso, que posso dizer que é uma ultima tentativa, que o jeito que estavamos estava muito bom e acho que conseguimos continuar assim e ser algo livre e leve. Acredito que os dois melhoraram bastante, e com você fazendo terapia também, pode ajudar a ter algo de novo... Tipo, não me sinto perdendo tempo por você não saber o que quer, as vezes acho que você nega muito seus sentimentos, eu vou te reconsquistar todos os dias se for necessario, eu ainda gosto muito de você e não só pela parte do amor, e sim pela paixão boba, que fico tenso de ta do seu lado. Vou te confessar que quero voltar a ficar com você sim, mas sem pensar em nada no futuro, para deixar acontecer o que tiver que acontecer.',

  '📅 05/11/2024 - Dia 40: Depois de tudo o que te falei hoje, dizer só "te amo" é pouco, vou falar uma frase do Dostoiévski: "sua mão é fria, a minha queima como fogo, como você é cega..." e também vou usar o video que me mandou para fazer essa parte. "Se eu te amo? eu te amo muito, talvez até mais que alguem consiga amar outra pessoa... Se eu tivesse que fazer igual o Henry, eu faria tudo de novo, de novo e de novo... Eu iria todos os dias no condominio para te ver, ver a sua playlist, ver seu tiktok com você sentado no banco, faria você usar a blusa amarela para irmos na sorveteria da avenida ipanema, falaria todas as coisas idiotas de novo e principalmente todas as coisas fofas, faria todos os dias sem me arrepender em nenhum momento. Mesmo eu concordando que você quer me apagar das suas memorias, por que pensa que me impediriade ter uma vida plena e feliz, mas saiba que faço as palavras do Henry, as minhas... Estar com você é o unico modo de eu ter uma vida plena e feliz, você é a garota dos meus sonhos."',

  '📅 06/11/2024 - Dia 41: Ainda não consegui comprar o carmed da hello kitty, mas vou achar kkkkkkkkkkkkk fiquei pensando no audio que mandou ontem a noite, me desculpa por insistir tanto, sei que to te forçando até demais com isso... Infelzimente todos os nossos momentos foram bem marcantes para mim e eu queria tentar de novo, mas eu quero que seja algo leve e sem pressão, mas sempre acabo colocando alguma pressão, me desculpa... Queria que tivesse furado a orelha hoje, mas o foda que dinheiro ta curto... Acho muito bonitinho você perguntando se "vou ir te ver", a resposta sempre vai ser claro que vou kkkkkkkkkkkk Dei bastante risada com a Emy e o Lucas, as vezes os dois são intakaveis',

  '🌕 EXTRA - SEMANA 06 🌕:',

  '📅 07/11/2024 - Dia 42: O dia de hoje foi bem legal e esquisito ao mesmo tempo, ainda mais com as pessoas da uniso me parando do nada para conversar (devo ter ima para gente doida). Não imaginei que iria te falar do sonho, que foi bem forte e o pior que ficam falando na minha cabeça que foi algo que aconteceu, tipo, não tem motivo para me deixar mal, a não ser o fato de me mostar você com saudade no sonho e me deixar como segunda opção por que tinha sido cancelado, isso foi foda, mas depois que falei com você, deu uma boa aliviada (obrigado por tanto) e confesso que não iria te falar nada... Me desculpa por não respeitar seu espaço nesses ultimos meses, é que eu só queria que fosse você, ou seja, eu vou te esperar, e quando quiser voltar já sabe... Não quero ser só seu amigo, me desculpa, mas pra mim é completamente impossivel manter só amizade com você sem criar expectativa, meio foda não acreditar que podemos tentar de novo, sendo que eu te amo tanto (não falo isso da boca pra fora).',

  '📅 08/11/2024 - Dia 43: O dia de hoje foi gostoso, gostei muito mais do que imaginei do filme, pena que a noite acabou uma merda... Falei de amanha fazer 2 meses que terminamos, mas confundi a data, é hoje! As fotos que eu tirei para marcar o lugar que você fez o segundo furo, vai ser uma lembrança boa, o seu olhinho brilhando com o vestido e confesso que to com vontade de te dar ele de presente.',

  '📅 09/11/2024 - Dia 44: Queria te mandar mensagem o dia todo, mas confesso que tava extremamente chateado/magoado com tudo que aconteceu ontem, ficou marcado na minha memoria você batendo a porta do carro e falando "não fode, Alan", e eu vim embora chorando igual criança, mano, eu só queria ter te dado um abraço antes de vir embora. Minha mãe e irmão perguntando de você o dia todo foi foda, ainda mais com o aniversario da Duda (obviamente que não falei nada), mas ficaram perguntando de você e separaram bolo e salgadinho para você, seu pai e Iris (salgadinho já amassei todos).',

  '📅 10/11/2024 - Dia 45: Fiquei esperando você falar para a gente se encontrar hoje, mesmo com tudo que aconteceu, confesso que tava bem ansioso para sairmos. Fui na minha tia perto da sua casa e enrolei um pouco só esperando a sua mensagem, mas sabia que não iria acontecer. Eu sonhei com você nos ultimos dias e cada sonho foi mais intenso que o outro, confesso que to muito mal por te magoado e por ta magoado também.',

  '📅 11/11/2024 - Dia 46: Confesso que hoje não passou nem um pouco pela minha cabeça que eu ia te ver, e esperava que fossemos ter uma conversa melhor, não só levar você para a casa e pronto, pareceu muito que eu fui só para te dar uma carona e foi isso. Na hora que saiu do carro, foi foda também, pra mim, você claramente bateu a porta do carro e tava brava com alguma coisa, só não quis me contar, mas como falou que tava tudo certo, então ta tudo certo...',

  '📅 12/11/2024 - Dia 47: Não imaginei que iria me convidar para ir no médico com você, e vou te confessar que fiquei meio relutante em ir (não sei te explicar o motivo), mas acabei indo por que sabia que ia ficar bem chatinha com o exame e iria se sentir mal de alguma forma, então quis te fazer companhia. Na hora que virou o olho pra mim, confesso que fiquei bem chateado, mas preferi só ficar em silencio e te fazer companhia. Acredito que tudo que te falei cedo é bem imporante e necessario, o que você vai fazer com a informação, já não sei, mas é isso...',

  '📅 13/11/2024 - Dia 48: Foi um dia bem merda pra mim, queria ter te visto (talvez nem faça tanta diferença pra você assim) pelo menos um pouco, mas não tinha condições de fazer algo de manha e você passou o dia todo sem falar comigo, então já "entendi" o recado, fora que tava numa bad fodida. Não tenho muito o que escrever sobre hoje, então é isso, um beijo da Anitta. ',

  '🌕 EXTRA - SEMANA 07 🌕:',

  '📅 14/11/2024 - Dia 49: Confundi os dias da sua consulta, queria ter ido com você para te ver, mas sei lá, ao mesmo tempo que você tava conversando comigo, senti você mais distante que o normal, será esse o famoso "preludio do fim"?. Na hora que vi sua chamada perdida, abri um sorrisinho, pensando que você tinha me ligado para querer falar comigo sobre qualquer coisa, queria companhia, sabe? Mas ai eu vi a mensagem que era pelo filme, assinei o teste gratis para vocês assistirem, tem bastante filme legal nessa plataforma...',

  '📅 15/11/2024 - Dia 50: Eu queria assistir esse filme com você, sozinho não assito nem fudendo (e não é nem meme), sei lá, quando me falou dele no cinema, pensei que seria algo "nosso" (nem sei se isso existe mais), até queria assistir para ter assunto com você, mas não vou mais te incomodar com minhas mensagens...',

  '📅 16/11/2024 - Dia 51: Nem lembrava que você ia vir em casa para ver o lance da documentação, de verdade mesmo, como ta bem distante de mim essa semana, já imaginei que nem ia querer mais me ver ou até mesmo tinha achado alguem para te ajudar com essas coisas. Queria sim te ver, passar tempo com você, eu sinto muito sua falta, mas é isso lek, tmj...',

  '📅 17/11/2024 - Dia 52: Teve um almoço em casa hoje, foi triste o pessoal perguntando o por que você não vinha também, que queriam te ver, falar com você e que você era boazinha. Enfim, acho que não sou unico que gosta de você... Eu vou te esperar (sei que não gosta dessa frase), mas eu vou viver minha vida, não quero só sua amizade, deixei claro e repito isso, quando eu for algo a mais que seu amigo, você me procura, que vai ter seu mistão quente, bolo e a armadilha de beijinhos... Bom, acho que isso nunca mais vai acontecer, já que foi facil não me amar mais, acho que vai ser facil não ter mais minha companhia... Só quero que você saiba que sinto sua falta e sempre quero te mandar mensagem para saber de você, conversar e zoar com você, mas sinto que só to forçando algo com você e que você não quer o mesmo, então é isso, sempre que quiser falar comigo, você tem carta branca para me procurar... Obrigado por tanto minha princesinha.'
]

let indice = 0

function mostrarFrase() {
  const elementoFrase = document.getElementById('frase')
  elementoFrase.innerText = frases[indice]
}

function mostrarProximaFrase() {
  indice = (indice + 1) % frases.length // Incrementa o índice e reinicia se chegar ao fim
  mostrarFrase()
}

function mostrarFraseAnterior() {
  indice = (indice - 1 + frases.length) % frases.length // Decrementa o índice e reinicia se for menor que 0
  mostrarFrase()
}

// Exibe a frase inicial ao carregar a página
document.addEventListener('DOMContentLoaded', mostrarFrase)
