const frases = [
  // 'Se a vida fosse um jogo, te amar seria o meu gol nos acréscimos, como nos jogos mais tensos do Curica.',

  // 'Eu amo amar você, nunca se esqueça disso...',

  '📅 25/09/2024 - Dia 00: Hoje foi um dia diferente de todos os outros, onde você me liga depois de uma briga com seu pai (confesso que achei estranho), eu queria muito te ver depois disso e ofereci carona para ir trabalhar, que por algum motivo sabia que era exatamente o que precisava. E ver você vestida de mostarda, nosso misto quente em um dos meus lugares favoritos só me fizeram ver o quão importante são esses momentos com você e nesse dia, posso dizer que me apaixonei(de novo). A noite, quando fomos no parque das aguas, foi uma noite diferente de tudo, ali tivemos conversas aleatorias, conversas sérias, brincamos, falamos mal dos outros, etc... uma noite perfeita (quero que todos nossos dias sejam assim). ',

  '📅 26/09/2024 - Dia 01: Depois do dia de ontem, eu queria muito te ver e então fiz a educação positiva para ter alguma forma de ver você (KKKKKKKKKKKKKK), e por sorte, você aceitou que eu te levasse para o trabalho (que manha maravilhosa), insisti para você meter o loko no trampo, eu queria muito ter sua companhia, não precisariamos fazer nada, só queria ta com você perto. O livro que baixei para você, vai ficar para sempre marcado como uma lembrança de você. Mesmo eu querendo muito, eu não imaginava que iriamos se ver de novo, e no fim você quis tomar sorvete e passar a noite comigo (que dia meu amigo), não deveriamos ter feito nada nesse dia, os dois estavam tensos,  aceleramos muito o processo e você acabou aceitando ser a minha ficante plus ultra master 4k.',

  '📅 27/09/2024 - Dia 02: Eu cheguei a sonhar com você nesse dia, e bateu uma saudade surreal (nem parecia que tinhamos se visto na noite anterior). Fiz educação positiva de novo e tive a melhor resposta que poderia ter recebido (você queria me ver tanto de manha quanto de noite). Essas manhãs se tornaram algo que quero fazer todos os dias, quero poder tomar café com você, te levar para o trabalho (até o dia que você vai ser minha esposa trofeu e não vai trabalhar nunca mais) ou seja, te ver todos os dias. A noite, quando fomos com o cice no shopping sorocaba, não sei explicar, mas tinha alguma coisa diferente ali e quando chegamos em casa, eu percebi que tava me sentindo muito mais confortavel com você do que nunca, tivemos sim uma conversa dificil (extremamente necessaria para o nosso recomeço) e de verdade? Quero muito finalizar ela para que possamos seguir juntos. Uma coisa que me falou a noite, eu entendi perfeitamente. Você vai amar alguém como me ama e vai receber um amor tão intenso quanto o meu (Spoiler: eu vou essa pessoa na sua vida). Não é por costume da rotina ou qualquer outra coisa, é pelo sentimento que um tem pelo outro, a pergunta que finalizei a noite, é justamente o que eu quero: ME DEIXA ENFRENTAR SEUS MEDOS COM VOCÊ?',

  '📅 28/09/2024 - Dia 03: Hoje foi um dia que eu queria muito te ver, muito mesmo (confesso que tava com saudades), mas queria também que aproveitasse o seu date (mesmo sabendo que ninguem é tão interessante quanto eu, tava com um pouco de ciumes). E quando você me chamou para sair, foi a melhor noticia que poderia ter tido e de verdade, a noite foi incrivel, mesmo eu tendo aquele sonho merda que me deixou bem abalado, a noite foi gostosa... Quero te pedir desculpas por quase falar as "tres palavras", perdi um pouco a linha. Quero ter mais noites como essa, você me permite ter?',

  '📅 29/09/2024 - Dia 04: Eu confesso que não ia te chamar para nada hoje, mas quando minha mãe falou para você almoçar em casa, só cedi aos pensamentos e te chamei (KKKKKKKKKKKKKKKKKKKK), mas ao mesmo tempo, queria que aproveitasse o seu momento e o seu dia (afinal, se vimos a semana toda), não deu certo da gente se ver, mas no final fiquei feliz com você usando educação positiva pra gente se ver amanhã. Eu fiquei muito puto hoje, parece que é crime eu fazer as coisas que eu quero com quem eu gosto, pqp... E no final da noite, quando a gente conversou até você dormir, eu gostei muito, foi muito gostoso, me acalmou e também foi diferente (não sei explicar)',

  '📅 30/09/2024 - Dia 05: Ainda bem que deixei para escrever no final do dia (KKKKKKKKKKKKKK), hoje aconteceu bastante "coisinhas", gostei muito do dia (por mais dias assim), não quero que pense que eu entendi errado as perguntas e tals, pelo contrario, eu entendi onde queria chegar com aquilo (são perguntas extremamentes importantes) e claramente que gostei de você falando que queria me ver, de falar que sou seu ficante ultra blaster 4k (KKKKKKKKKKKKK), confesso que fiquei com um pouco de medo da nossa conversa no final do dia, mas o que eu falei é sério, guarde somente as coisas boas do nosso relacionamento e vamos construir algo do zero, por isso que o "dia00" foi no dia 25/09/2024, que nesse dia algo mudou e acho que ali foi um marco. ',

  '📅 01/10/2024 - Dia 06: Não sei explicar o que eu senti nesse dia, mas foi algo bom. Eu falando abertamente o que eu queria fazer e a noite, mesmo com pouco tempo juntos, foi maravilhoso, sério mesmo. As consultas com a psicologa me ajudam a cada vez mais entender meu sentimento por você e com tudo o que ta acontecendo, e cada dia que passa você se torna mais e mais importante na minha vida (sempre foi, mas agora é diferente), falo com toda certeza que você é uma das coisas mais importante na minha vida. O que eu falei ontem sobre o salto que minha vida pode dar é verdade, e é tudo graças a você, justamente por isso que eu não acredito que tudo que aconteceu entre a gente seja algo passageiro, eu acho que você é alguém para ficar (quero que fique)... Eu espero muito que no nosso recomeço você seja a minha esposa trofeu e escolha ficar comigo até eu ficar bem velhinho e que possamos viajar o mundo juntos e fazer todos nossos planos darem certos (são muitos)...',

  '📅 02/10/2024 - Dia 07: Queria ter visto o eclipse com você, mas quase não deu para ver em SP. O dia todo foi maravilhoso, principalmente o fato da gente tomar café juntos e queria muito ter uma foto sua com a florzinha na orelha, ainda mais hoje que tava toda menininha, ficou perfeito (HOJE ME APAIXONEI UM POUCO MAIS POR VOCÊ). Confesso que fiquei pensando na volta do seu ex maluco, ele me deixou muito puto com tudo que te falou (maluco babaca) e confesso também que me deixou com um pouco de ciumes (KKKKKKKKKKKKKKKK), mas quando ele falou de "ficantezinho" e começou a meio que te ofender o sangue subiu na hora, acho que faria merda real se encontrasse com ele. Fiquei pensando também que você meio bebada e eu ainda sim cuidando de você para não dar muito na cara que tava triloca. Vou te confessar outra coisa com base nisso, o que eu falei é verdade, se fosse o "meu antigo eu", eu iria ficar puto com você e talvez iriamos ter uma leve discussão por causa disso, mas eu achei engraçado e fiz o que sempre deveria ter feito quando fosse o caso CUIDAR DE VOCÊ e não te julgar (E isso só me fez desenrolar mais o que eu sinto)... ',

  '🌑 EXTRA - SEMANA 01 🌑: Essa primeira semana da gente foi maravilhosa, pode parecer que não, mas você me mostrou bastante coisa do que eu quero (acredito que sejam atitudes involuntarias), confesso que tava negando muito meus sentimentos, mas depois que meu amigo falou que a gente ta num dos melhores momentos que poderiamos estar, que é a fase de se conhecer de novo (fiquei pensando muito nisso), eu sei que a gente já ta se conhecendo de novo, mas quero que deixar bem claro que vou tentar te reconquistar todos os dias da minha vida até você chegar no momento que vai falar que não quer mais me ver nem pintado de ouro (eu apareco pintado de prata ou verde KKKKKKKKKKKKKKKKK), você já sabe de tudo isso, né? Então Yasmin, eu vou te esperar, não quero conhecer ninguem, então saiba que... caso você me permita ter você de novo num relacionamento, eu to esperando com bolo, coquinha de café e seu mistão quente... Volto a dizer, o nosso recomeço tem tudo para ser lindo, você já viu o quanto to diferente, ou seja, aquele Alan que conheceu, morreu e nunca mais vai voltar. Sei que ta confusa, quer desenrolar os sentimentos, aproveitar a vida e tals, mas independente de tudo, quero enfrentar tudo com você e te provar como seremos melhores juntos... OBRIGADO POR SER ESSA PESSOA INCRIVEL NA MINHA VIDA, MEU PUDINZINHO KKKKKKKKKKKKKK ',

  '📅 03/10/2024 - Dia 08: O dia de hoje foi diferente de tudo, confesso que achei bonitinho você com medo de eu cansar de você  KKKKKKKKKKKKKKKKK (não vou cansar e nem desistir de você, saiba que vou te esperar o tempo que for necessario, e não esqueça, eu to no seu podio). eu me emocionei com o que me falou sobre mim, não esperava que ia me sentir tão feliz com o que me falou a ponto de chorar (quanto tempo que isso não acontece), principalmente quando falou que iria contar sobre mim para seus filhos e neto (porra, isso me pegou demais. foi de longe a coisa mais bonita que alguém falou de mim)... nossa conversa foi necessaria e de novo, eu sei que não ta pronta namorar de novo por varios motivos e que estamos se conhecendo de novo, mas ainda aguardo ansiosamente o dia que vai me procurar para tentarmos de novo... espero que possamos ir alinhando tudo ao decorrer dos meses para que possamos seguir novamente juntos, e no final, eu concordo com você é "cedo demais", fiquei pensando sobre isso e concordo com quase tudo que falou, só não concordo com o que falou de voltarmos agora e ser tudo bom e voltar a ser zoado (eu duvido que isso aconteceria de novo), mas saiba que você tem meu coraçãozinho pra você, e sempre vai ter. meu unico pedido é para que não vá embora da minha vida, eu sempre vou querer sua companhia... cara, você tem noção do quão importante você é pra mim?????? vou te esperar o tempo que for e não te falei, mas vou eternizar você no meu corpo junto com a tatugem do maktub que gosta... espero que não fique um clima zoado entre a gente e saiba que to aqui para enfrentar todos os seus medos e inseguranças para que possamos ser um casalzão da porra (KKKKKKKKKKKKKKKKKK). obrigado por tanto, não sei como te agradecer, acho que se eu te der o mundo não é o suficiente para te mostar o quão imporante você é, mas é isso lek, tmj',

  '📅 04/10/2024 - Dia 09: Quero começar isso aqui te pedindo desculpas por ta chatinho na hora que te encontrei a noite (queria muito te ver), achei muito fofinho você se preocupando comigo e segurando minha mão (tão fofinhaaaa)... eu não tinha pensado no que falou sobre a gente no inicio de tudo, que você também não queria um relacionamento e mudou de ideia, quero que seja livre e leve, não com pressão nem nada do genero. Só para você ter certeza, não vou embora da sua vida e não quero que você va embora também (quero você comigo quando eu conquistar o mundo), e para deixar eternizado, eu penso em você todos os dias e o tempo todo, você não precisa fazer nada para isso acontecer. E ai gatinha, ta afim de viver um romance periculoso comigo???? (KKKKKKKKKKKKK)',

  '📅 05/10/2024 - Dia 10: Hoje foi um dia que nem conversamos direito (senti sua falta pra caralho), mas eu sei que tava curtindo o rolê com sua familia e espero muito que seu dia tenha sido muito, muito, muito, mas muito bom mesmo... Confesso que fiquei imaginando como seria eu com você em SP, conhecendo seus familiares e a gente se divertindo junto (será que isso um dia vou ter essa oportunidade de novo?). O lance do meu pai me deixou desconfortavel, que eu sei que a ideia dele é boa, mas porra, ficar te enchendo o saco assim, você já tem muita gente que te enche o dia todo (eu me incluo nisso), foi mal, de verdade... Nem preciso falar que queria muito te ver hoje e provavelmente amanha também sinta essa mesma vontade, mas eu sei que quer passar esse seu tempo com você mesmo... Meu sonho de princesa seria você me chamar amanha para ir votar com você KKKKKKKKKKKKKKKKK',

  '📅 06/10/2024 - Dia 11: Infelizmente meu sonho de princesa não se realizou, mas tudo bem (ou não) KKKKKKKKKKKKKK. Fiquei muito feliz em saber que sua familia acabou perguntando de mim, mas ao mesmo tempo fiquei meio pá pensando que isso poderia ter sido um incomodo de alguma forma (sei lá, minha cabeça não para tem hora), e fiquei muito contente de trazer o sabonetinho de lembrança pra mim (não sei explicar o que senti, mas o coração ficou quentinho). Quando eu fui votar, eu lembrei de como eu tinha planejado esse dia com você, que era você me acompanhando na votação aqui perto de casa, a gente almoçando juntos e a tarde indo votar com você para passar o dia juntos assistindo filme. E quando você usando de estrategias ardilosas para eu te buscar amanha, foi muito bonitinho KKKKKKKKKKKKKK',

  '📅 07/10/2024 - Dia 12: Sabe, hoje foi diferente... Principalmente quando "mandou" eu ir te buscar e eu só aceitei KKKKKKKKKKKKKKK, nós passamos de certa forma, o dia todo juntos e foi muito gostoso e engraçado, quando eu soprei sua boca e sua barriguinha foi enchendo parecendo um balão, foi intankavel pra mim (vou fazer mais vezes isso, gostei). Quero ter muito mais dias assim... Na hora que fomos na demarto, comprar remedio e tudo mais, senti uma coisa bem diferente, não sei dizer exatamente o que é, mas foi algo gostoso de sentir (acho que to apaixonado por você(só acho))... ',

  '📅 08/10/2024 - Dia 13: Quando fui te buscar e percebi a cara que você tava para fazer o exame, confesso que fiquei com medo, parecia que iria a qualquer momento me matar e me comer (mas ainda sim tava brincando com o perigo KKKKKKKKKKKK) e na hora que você amassou os lanches, fiquei extremamente surpreso e a foto que tirei, vai ficar marcado pra sempre como "o dia que alimentei meu dragãozinho" KKKKKKKKKKKKKKKKKKKKKK Queria ter passado o resto do dia com você, mas só não falei para fazer isso, por que tinha que fazer suas coisinhas na sua casa, mas saiba que era o que mais queria.',

  '📅 09/10/2024 - Dia 14: Cara, não tenho palavras para o dia de hoje, aconteceu quase tudo que poderia acontecer num dia (sério mesmo). Não gostei de passar esse dia com você, eu amei passar ele com você (não tiraria nada do que aconteceu). Eu senti muito que eramos um casal (peço até desculpas se em algum momento eu confundi as coisas), mas isso é para você ter uma noção de como seria caso você libere uma vaguinha de namorado ai KKKKKKKKKKKKKK (não esqueci que sou o dono do primeiro lugar). Quero ter muito mais dias com você assim, sério mesmo... A unica coisa que eu posso garantir, é que vai ser cada dia melhor...',

  '🌒 EXTRA - SEMANA 02 🌒:  E assim fechamos a nossa segunda semana desde que se "conhecemos", não posso dizer que tivemos altos e baixos, que estamos basicamente em perfeita sintonia. A parada com a minha mãe mexeu muito comigo, mas eu sei que é extremamente necessario o que ela falou e saiba que não tem motivo de você parar de vir em casa, até por que eu sei que ela não iria ligar e eu to falando sério com isso (sempre que quiser vir, você sempre vai ser bem recebida). Sabe, eu acho que da forma que estamos indo, ta fluindo muito bem e concordo que ainda é cedo para voltar, alias deu só 1 mês que estamos separados (obviamente que deu para notar a diferença em ambos), mas saiba que eu vou continuar melhorando por mim acima de tudo, mas claramente é com aquele fiozinho de esperança que o nosso recomeço vai ser lindo, saiba que eu vou esperar você ficar pronta para assumir um relacionamento de novo e não vou me arrepender nem um pouco disso, então Yasmin, eu to te esperando aqui para você ser minha esposa troféu!',

  '📅 10/10/2024 - Dia 15: O dia foi muito bom (como vem sendo todos os dias), a minha lembrança favorita agora é da gente tomando café em um dos meus lugares favoritos (quero ter muito mais dias assim)... Eu gosto de fazer tudo com você, te buscar/levar para o trabalho, te irritar, cuidar de você, tomar café com você, te abraçar, te cheirar, enfim, tudo... O que eu falei de noite é verdade, não quero ninguem melhor pra mim, quero que você se torne a melhor pessoa pra mim, da mesma forma que não quero que você encontre alguém melhor que eu, eu vou ser o melhor pra você. Sei que algumas coisas que eu falei foram "pesadas", e não, não vou te pedir desculpas por isso, meu unico pedido é para que me deixe mostrar o meu amor para você e te provar que você merece sim ser amada... Eu não quero ficar nem um dia sem falar com você, quero falar e te ver todos os dias da minha vida, até ficar bem velhinho, então, pare de loucura e me deixe entrar para enfretar tudo o que tem medo/insegurança junto com você.',

  '📅 11/10/2024 - Dia 16: Mesmo sendo rapidinho, gostei de ter comido o mistão com você KKKKKKKK e to extremamente ansioso para irmos para SP juntos, acho que vai ser bem gostoso.... quero ir no parque da juventude com você e conhecer o museu, quero fazer muitas coisas com você lá... Mesmo eu te vendo de manha, confesso que fiquei meio chateado por não te ver a noite, que você quis ir com seu pai e quando sumiu, fiquei mais chateado ainda, senti que meio que não queria minha companhia, sei lá, algo desse genero, sabe... Enfim, quando apareceu a noite e me contou o que foi, fiquei mais aliviado que você tava bem, mas ainda me sentindo meio esquisito (loucura né? KKKKKKKKKKKKKK)',

  '📅 12/10/2024 - Dia 17: Confesso que tava animado para ir com você na espaço laser, mas quando desmarcou ontem, eu já sabia que não iria te ver hoje (foda), queria ter passado o dia com você, mesmo sabendo que iriamos passar o dia todo juntos amanhã... E quando te chamei, minha mãe pediu para comprar sorvete e falou "pega um que a Yasmin goste também, vai que ela venha aqui, pelo menos tem algo gostoso para ela", e confesso que tinha esquecido do seu compromisso...',

  '📅 13/10/2024 - Dia 18: Cara, hoje não tenho como te explicar o quão gostoso foi o dia, sério mesmo, não tenho palavras para descrever e tenho uma cena marcada na minha cabeça, que é você andando na paulista toda contente, animada com tudo que via, sério, isso pra mim foi a melhor coisa que poderia ter acontecido... Sei que em alguns momentos não fui uma companhia tão boa, mas eu só tava com medo de estragar o dia, que quase fiz isso... Espero que sempre lembre desse dia e que possamos ter mais dias assim, foi incrivel com TODAS AS LETRAS, OBRIGADO POR SER TÃO BOA PRA MIM (MESMO EU NÃO MERECENDO)',

  '📅 14/10/2024 - Dia 19: Hoje fiquei meio pa, por que queria ir te buscar para ir trabalhar e te ver um pouco (acho que era necessario depois de ontem), mas fiquei muito feliz de você querer me ver a noite para conversarmos (você ta me devendo um abraço), pena que a reunião atrapalhou nossa conversa, mas conseguimos conversar e se ver um pouquinho, foi bom...',

  '📅 15/10/2024 - Dia 20: Por mais que eu tava meio pa, gostei de ter ido te levar trabalhar (faltou só levar seu mistão) e sério, fiquei muito pensativo com a merda que te falei do "relacionamento CLT", sei que não é assim e nunca foi, não quero te cobrar de falar comigo (você não tem obrigação nenhuma de me responder). Confesso que não quero parar de ficar com você, quero continuar até você ir embora, mas vou respeitar sua decisão (só não quero que você fique sem falar comigo), sei que você tava bem ocupada, mas ainda sim senti muita sua falta durante o dia.',

  '📅 16/10/2024 - Dia 21: Hoje percebi que você não tava muito afim de conversar comigo e confesso que queria muito te mandar mensagem, mas por algum motivo sei que você só não ta no clima para conversar comigo (e ta tudo bem, ou não). Gostei de ter feito o monstrão quente para você, é minha nova especialidade para te mimar um pouco ou fazer seu café da manhã KKKKKKKKKKKKK espero que você esteja lendo ainda isso aqui e que fale comigo (to com medo de te incomodar, se mandar mensagem)... Obrigado por tanto, não desiste de mim, ta?',

  '🌒 EXTRA - SEMANA 03 🌒:'
]

let indice = 0

function mostrarFrase() {
  const elementoFrase = document.getElementById('frase')
  elementoFrase.innerText = frases[indice]
}

function mostrarProximaFrase() {
  indice = (indice + 1) % frases.length // Incrementa o índice e reinicia se chegar ao fim
  mostrarFrase()
}

function mostrarFraseAnterior() {
  indice = (indice - 1 + frases.length) % frases.length // Decrementa o índice e reinicia se for menor que 0
  mostrarFrase()
}

// Exibe a frase inicial ao carregar a página
document.addEventListener('DOMContentLoaded', mostrarFrase)
